# All additional integrations should be added following this format only.

services:
  nuclei_analyzer:
    image: khulnasoft/nuclei_analyzer:${REACT_APP_THREATMATRIX_VERSION}
    container_name: nuclei_analyzer
    restart: unless-stopped
    expose:
      - "4008"
    env_file:
      - env_file_integrations
    volumes:
      - generic_logs:/var/log/threat_matrix
    depends_on:
      - uwsgi
