services:
  bbot_analyzer:
    image: khulnasoft/threatmatrix_bbot_analyzer:${REACT_APP_THREATMATRIX_VERSION}
    container_name: threatmatrix_bbot_analyzer
    restart: unless-stopped
    expose:
      - "5001"
    volumes:
      - generic_logs:/var/log/threat_matrix
    depends_on:
      - uwsgi
