# All additional integrations should be added following this format only.

services:
  bbot_analyzer:
    build:
      context: ../integrations/bbot
      dockerfile: Dockerfile
    image: khulnasoft/threatmatrix_bbot_analyzer:test
