version: '3.8'

services:
  cyberchef-server:
    image: khulnasoft/threatmatrix_cyberchef:${REACT_APP_THREATMATRIX_VERSION}
    container_name: threatmatrix_cyberchef
    restart: unless-stopped
    expose:
      - '3000'
    depends_on:
      - uwsgi
