services:
  phunter:
    image: khulnasoft/threatmatrix_phunter:${REACT_APP_THREATMATRIX_VERSION}
    container_name: threatmatrix_phunter
    restart: unless-stopped
    expose:
      - "5612"
    volumes:
      - generic_logs:/var/log/threat_matrix
    depends_on:
      - uwsgi