name: "Generate ThreatMatrix People"
description: "Generate the data for the ThreatMatrix People page"
author: "KhulnaSoft DevOps <info@khulnasoft.com>"
inputs:
  token:
    description: 'User token, to read the GitHub API. Can be passed in using {{ secrets.ORG_REPO_TOKEN }}'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
