services:
  thug:
    image: khulnasoft/threatmatrix_thug:${REACT_APP_THREATMATRIX_VERSION}
    container_name: threatmatrix_thug
    restart: unless-stopped
    expose:
      - "4002"
    env_file:
      - env_file_integrations
    volumes:
      - generic_logs:/var/log/threat_matrix
    depends_on:
      - uwsgi

